### PR TITLE
Fix the navigation

### LINKED ISSUE #5: Improve the navigation
I already see there are some issues with the navigation's design, such as:
1. User should be able to navigate to "Details" view from Shrinked view as well, not only from the Expanded view,
2. Having both "Back" and "Less" navigation buttons is super confusing - navigation from details view should not contain the possibility to directly navigate to Shrinked view.
This will most likely be covered by 1st point though,
3. All types of navigation buttons should have better design and feel, also they should be unified, with emphasized navigation destination

### PR DESCRIPTION
**Pull request by BartoszKlonowski**
This pull request closes #5

### CODE REVIEW

File: app/src/popup/Popup.tsx [hunk 1]
```diff
@@ -17,13 +18,19 @@ export const Popup = (): JSX.Element => {
...
     return (
         <div className="popup-view">
-            {expanded ? <ExpandedView setSortingOrder={setSortingOrder} sorted={order} /> : <ShrinkedView />}
-            <Button
-                label={expanded ? "shrink-button-label" : "expand-button-label"}
-                onClick={() => {
-                    setExpanded(!expanded);
-                }}
-            />
+            {expanded ? (
```
Comment (BartoszKlonowski) [inline app/src/popup/Popup.tsx:21]: Initially this was the idea of handling a navigation in SPA-like add-on, however, currently I start to recognize some major problems with it.
For now, let it stay as it is, but this part of code should utilize the react-router at least.

File: app/src/popup/subcomponents/ShrinkedView.tsx [hunk 2]
```diff
@@ -47,17 +54,37 @@ export const ShrinkedView = () => {
 
     return (
         <>
```
Comment (BartoszKlonowski) [inline app/src/popup/subcomponents/ShrinkedView.tsx:56]: `Fragment` could be used here.

File: app/src/popup/subcomponents/ShrinkedView.tsx [hunk 3]
```diff
@@ -47,17 +54,37 @@ export const ShrinkedView = () => {
...
+            {detailsScreenWebsite ? (
+                <DetailsView
+                    website={detailsScreenWebsite}
+                    onBackButtonClick={() => {
+                        setDetailsScreenWebsite(null);
+                        setDetailsScreen(false);
+                    }}
+                />
+            ) : (
+                <div className="shrinked-view-container">
```
Comment (BartoszKlonowski) [inline app/src/popup/subcomponents/ShrinkedView.tsx:67]: Whole `ShrinkedView` looks more and more like a tile of `ExtendedView`. Maybe there will be a time to make a shared component out of it.
